<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

class DashboardController extends Controller
{
    /**
     * Display the Tanggapin operational dashboard.
     */
    public function index(Request $request): Response
    {
        return Inertia::render('dashboard', [
            'stats' => [
                'studentsNeedingAttention' => 12,
                'activeCases' => 4,
                'overdueCases' => 2,
                'dataCheckIssues' => 7,
                'duePayments' => 18,
                'activeIncidents' => 1,
                'resolvedThisMonth' => 24,
            ],
            'priorityFeed' => [
                [
                    'id' => 'alert-1',
                    'studentId' => 'std-101',
                    'studentName' => 'Brian Aditya',
                    'class' => 'XI RPL 2',
                    'riskLevel' => 'high',
                    'triggerType' => 'Kehadiran & Nilai',
                    'summary' => 'Kehadiran menurun drastis (28% ketidakhadiran dalam 14 hari) dan 2 tugas produktif belum terkumpul.',
                    'actionTaken' => false,
                    'suggestedAction' => 'Buat Follow-up & Hubungi Orang Tua',
                    'parentName' => 'Hadi Wicaksono',
                    'parentPhone' => '+62 812-3456-7890',
                    'homeroomTeacher' => 'Hendra Setiawan, S.Pd',
                    'timestamp' => '10 menit lalu',
                ],
                [
                    'id' => 'alert-2',
                    'studentId' => 'std-102',
                    'studentName' => 'Ahmad Fauzan',
                    'class' => 'X TKJ 1',
                    'riskLevel' => 'high',
                    'triggerType' => 'Pola Kedisiplinan',
                    'summary' => 'Terdeteksi pola pelanggaran berulang: 3x terlambat berurutan dan atribut seragam tidak lengkap. Total 35 poin.',
                    'actionTaken' => false,
                    'suggestedAction' => 'Catat Pembinaan & Rujuk Konseling BK',
                    'parentName' => 'Rukmini Fauzan',
                    'parentPhone' => '+62 813-8899-1122',
                    'homeroomTeacher' => 'Dewi Sartika, M.Kom',
                    'timestamp' => '35 menit lalu',
                ],
                [
                    'id' => 'alert-3',
                    'studentId' => 'std-103',
                    'studentName' => 'Siti Nurhaliza',
                    'class' => 'XII AKL 2',
                    'riskLevel' => 'medium',
                    'triggerType' => 'Penurunan Akademik',
                    'summary' => 'Nilai simulasi kejuruan dan matematika mengalami penurunan >20 poin dari rata-rata sebelumnya.',
                    'actionTaken' => false,
                    'suggestedAction' => 'Jadwalkan Konsultasi Belajar & Matrikulasi',
                    'parentName' => 'Bambang Sudirman',
                    'parentPhone' => '+62 821-4433-2211',
                    'homeroomTeacher' => 'Sri Wahyuni, S.E',
                    'timestamp' => '2 jam lalu',
                ],
                [
                    'id' => 'alert-4',
                    'studentId' => 'std-104',
                    'studentName' => 'Deni Saputra',
                    'class' => 'XI TKR 3',
                    'riskLevel' => 'high',
                    'triggerType' => 'Risiko ATS (Drop-out)',
                    'summary' => '3 pekan tidak hadir tanpa keterangan. Kunjungan lapangan pertama dijadwalkan oleh tim ATS.',
                    'actionTaken' => false,
                    'suggestedAction' => 'Verifikasi Lapangan & Kunjungan Rumah',
                    'parentName' => 'Suparman',
                    'parentPhone' => '+62 856-7788-9900',
                    'homeroomTeacher' => 'Gunawan, S.T',
                    'timestamp' => '4 jam lalu',
                ],
            ],
            'classes' => [
                [
                    'id' => 'cls-1',
                    'name' => 'XI RPL 2',
                    'major' => 'Rekayasa Perangkat Lunak',
                    'homeroomTeacher' => 'Hendra Setiawan, S.Pd',
                    'totalStudents' => 36,
                    'attendanceRate' => 91,
                    'studentsAtRisk' => 3,
                    'pendingFollowups' => 2,
                    'healthStatus' => 'warning',
                ],
                [
                    'id' => 'cls-2',
                    'name' => 'X TKJ 1',
                    'major' => 'Teknik Komputer & Jaringan',
                    'homeroomTeacher' => 'Dewi Sartika, M.Kom',
                    'totalStudents' => 34,
                    'attendanceRate' => 88,
                    'studentsAtRisk' => 4,
                    'pendingFollowups' => 3,
                    'healthStatus' => 'critical',
                ],
                [
                    'id' => 'cls-3',
                    'name' => 'XII AKL 2',
                    'major' => 'Akuntansi & Keuangan Lembaga',
                    'homeroomTeacher' => 'Sri Wahyuni, S.E',
                    'totalStudents' => 35,
                    'attendanceRate' => 97,
                    'studentsAtRisk' => 1,
                    'pendingFollowups' => 0,
                    'healthStatus' => 'good',
                ],
                [
                    'id' => 'cls-4',
                    'name' => 'XI TKR 3',
                    'major' => 'Teknik Kendaraan Ringan',
                    'homeroomTeacher' => 'Gunawan, S.T',
                    'totalStudents' => 32,
                    'attendanceRate' => 86,
                    'studentsAtRisk' => 4,
                    'pendingFollowups' => 4,
                    'healthStatus' => 'critical',
                ],
            ],
            'cases' => [
                [
                    'id' => 'case-01',
                    'code' => 'CS-2025-089',
                    'studentName' => 'Rian Pratama',
                    'class' => 'XI RPL 1',
                    'category' => 'Kedisiplinan',
                    'priority' => 'Tinggi',
                    'stage' => 'in_progress',
                    'stageLabel' => 'Sedang Ditangani',
                    'assignee' => 'Ibu Rahmawati (Guru BK)',
                    'lastActivity' => 'Konseling sesi ke-2 selesai, dibuat surat komitmen bersama.',
                    'lastUpdate' => 'Hari ini, 09:15',
                    'timeline' => [
                        ['time' => '22 Sep 08:30', 'title' => 'Case dibuat oleh Wali Kelas', 'actor' => 'Wali Kelas XI RPL 1'],
                        ['time' => '22 Sep 10:00', 'title' => 'Ditugaskan ke Guru BK', 'actor' => 'Koordinator BK'],
                        ['time' => '23 Sep 13:00', 'title' => 'Konseling tatap muka sesi 1', 'actor' => 'Ibu Rahmawati (BK)'],
                        ['time' => '24 Sep 09:15', 'title' => 'Komunikasi & Panggilan Orang Tua', 'actor' => 'Ibu Rahmawati (BK)'],
                    ],
                ],
                [
                    'id' => 'case-02',
                    'code' => 'CS-2025-090',
                    'studentName' => 'Alisa Putri Melati',
                    'class' => 'X DKV 2',
                    'category' => 'Sosial & Perlindungan',
                    'priority' => 'Tinggi',
                    'stage' => 'assigned',
                    'stageLabel' => 'Ditugaskan',
                    'assignee' => 'Bpk. Faisal (BK)',
                    'lastActivity' => 'Menunggu penjadwalan mediasi dengan orang tua.',
                    'lastUpdate' => 'Kemarin, 14:20',
                    'timeline' => [
                        ['time' => '23 Sep 11:20', 'title' => 'Laporan indikasi perundungan diterima', 'actor' => 'Wali Kelas'],
                        ['time' => '23 Sep 14:00', 'title' => 'Verifikasi awal dan perlindungan siswa', 'actor' => 'Kesiswaan'],
                        ['time' => '24 Sep 08:00', 'title' => 'Ditugaskan penanganan ke BK', 'actor' => 'Kepala Sekolah'],
                    ],
                ],
                [
                    'id' => 'case-03',
                    'code' => 'CS-2025-091',
                    'studentName' => 'Fajar Nugraha',
                    'class' => 'XI TKR 2',
                    'category' => 'Akademik',
                    'priority' => 'Sedang',
                    'stage' => 'follow_up',
                    'stageLabel' => 'Perlu Follow-up',
                    'assignee' => 'Bpk. Gunawan, S.T',
                    'lastActivity' => 'Jadwal matrikulasi perbaikan nilai praktik mesin.',
                    'lastUpdate' => '2 hari lalu',
                    'timeline' => [
                        ['time' => '20 Sep 10:00', 'title' => 'Case akademik dibuat', 'actor' => 'Guru Produktif'],
                        ['time' => '21 Sep 11:30', 'title' => 'Pemberian modul perbaikan', 'actor' => 'Guru Produktif'],
                        ['time' => '23 Sep 15:00', 'title' => 'Ujian perbaikan belum tuntas', 'actor' => 'Guru Produktif'],
                    ],
                ],
                [
                    'id' => 'case-04',
                    'code' => 'CS-2025-092',
                    'studentName' => 'Dimas Maulana',
                    'class' => 'XII RPL 1',
                    'category' => 'Kehadiran',
                    'priority' => 'Tinggi',
                    'stage' => 'new',
                    'stageLabel' => 'Baru Masuk',
                    'assignee' => 'Belum Ditugaskan',
                    'lastActivity' => 'Peringatan otomatis sistem: tidak hadir 5 hari berturut-turut.',
                    'lastUpdate' => 'Hari ini, 07:45',
                    'timeline' => [
                        ['time' => '24 Sep 07:45', 'title' => 'Pemicu otomatis Early Warning aktif', 'actor' => 'Sistem Tanggapin'],
                    ],
                ],
            ],
            'atsList' => [
                [
                    'id' => 'ats-1',
                    'studentName' => 'Deni Saputra',
                    'lastClass' => 'XI TKR 3',
                    'address' => 'Kp. Sukamaju RT 03/05, Desa Sukaresmi',
                    'officer' => 'Bpk. Ahmad (Tim Satgas ATS)',
                    'status' => 'Kunjungan Terjadwal',
                    'reason' => 'Kendala ekonomi & membantu usaha keluarga',
                    'scheduledVisit' => '27 Sep 2025, 14:00',
                ],
                [
                    'id' => 'ats-2',
                    'studentName' => 'Maya Anggraini',
                    'lastClass' => 'X AKL 1',
                    'address' => 'Jl. Merpati No. 14, Kel. Jatirasa',
                    'officer' => 'Ibu Nurul (Tim Satgas ATS)',
                    'status' => 'Intervensi Bantuan PIP',
                    'reason' => 'Masalah biaya transportasi sekolah',
                    'scheduledVisit' => 'Sudah diverifikasi (22 Sep)',
                ],
            ],
            'paymentList' => [
                [
                    'id' => 'pay-1',
                    'invoiceNo' => 'INV-2025-09-001',
                    'studentName' => 'Reza Pahlevi',
                    'class' => 'XI RPL 2',
                    'type' => 'SPP September 2025',
                    'amount' => 350000,
                    'dueDate' => '10 Sep 2025',
                    'status' => 'Terlambat',
                ],
                [
                    'id' => 'pay-2',
                    'invoiceNo' => 'INV-2025-09-002',
                    'studentName' => 'Anisa Salma',
                    'class' => 'X TKJ 1',
                    'type' => 'SPP September 2025',
                    'amount' => 350000,
                    'dueDate' => '10 Sep 2025',
                    'status' => 'Menunggu Verifikasi',
                ],
                [
                    'id' => 'pay-3',
                    'invoiceNo' => 'INV-2025-09-003',
                    'studentName' => 'Bayu Wicaksono',
                    'class' => 'XII AKL 2',
                    'type' => 'Uang Praktik Kejuruan',
                    'amount' => 200000,
                    'dueDate' => '15 Sep 2025',
                    'status' => 'Lunas',
                ],
            ],
            'dapodikIssues' => [
                [
                    'id' => 'dap-1',
                    'category' => 'Tugas Tambahan Guru',
                    'targetName' => 'Drs. Subagyo (NIP. 19740512...)',
                    'field' => 'SK Pembina Ekstrakurikuler',
                    'description' => 'SK belum terunggah di riwayat penugasan semester ganjil.',
                    'severity' => 'Error',
                    'action' => 'Unggah dokumen SK & nomor referensi',
                ],
                [
                    'id' => 'dap-2',
                    'category' => 'Data Siswa',
                    'targetName' => 'Farhan Alamsyah (NISN: 0078129381)',
                    'field' => 'NIK Orang Tua Kosong',
                    'description' => 'Data NIK Ayah dan Ibu belum terisi pada form registrasi awal.',
                    'severity' => 'Perlu Diperiksa',
                    'action' => 'Kirim reminder update data ke orang tua',
                ],
                [
                    'id' => 'dap-3',
                    'category' => 'Rombongan Belajar',
                    'targetName' => 'Kelas XI TKR 3',
                    'field' => 'Mata Pelajaran PKn Tanpa Pengampu',
                    'description' => 'Jadwal rombel belum dipetakan ke guru mata pelajaran terdaftar.',
                    'severity' => 'Error',
                    'action' => 'Petakan guru pengampu di menu pembelajaran',
                ],
            ],
            'documents' => [
                [
                    'id' => 'doc-1',
                    'title' => 'Modul Ajar Pemrograman Web & Perangkat Bergerak',
                    'teacher' => 'Hendra Setiawan, S.Pd',
                    'category' => 'Perangkat Pembelajaran',
                    'period' => '2025/2026 Ganjil',
                    'status' => 'Lengkap',
                    'size' => '2.4 MB',
                ],
                [
                    'id' => 'doc-2',
                    'title' => 'SK Pembagian Tugas Guru & Tugas Tambahan BK',
                    'teacher' => 'Rahmawati, S.Pd (BK)',
                    'category' => 'SK & Penugasan',
                    'period' => '2025/2026 Ganjil',
                    'status' => 'Lengkap',
                    'size' => '1.1 MB',
                ],
                [
                    'id' => 'doc-3',
                    'title' => 'Sertifikat Pelatihan Kurikulum Merdeka Terintegrasi',
                    'teacher' => 'Dewi Sartika, M.Kom',
                    'category' => 'Sertifikat Diklat',
                    'period' => 'Agustus 2025',
                    'status' => 'Terverifikasi',
                    'size' => '850 KB',
                ],
            ],
            'incidents' => [
                [
                    'id' => 'inc-1',
                    'title' => 'Prosedur Siaga Bencana Musim Hujan & Banjir Genangan',
                    'type' => 'Cuaca Ekstrem',
                    'status' => 'Siaga Aktif',
                    'level' => 'Waspada',
                    'leadOfficer' => 'Bpk. Harun (Ketua Tim K3 & Tanggap Darurat)',
                    'checklist' => [
                        ['id' => 'chk-1', 'label' => 'Aktivasi Tim Tanggap Darurat Sekolah', 'done' => true],
                        ['id' => 'chk-2', 'label' => 'Pemeriksaan Drainase Lapangan & Gedung B', 'done' => true],
                        ['id' => 'chk-3', 'label' => 'Pengamanan Dokumen Arsip & Server di Lantai 2', 'done' => true],
                        ['id' => 'chk-4', 'label' => 'Penyusunan Rute Alternatif Pulang Siswa', 'done' => false],
                        ['id' => 'chk-5', 'label' => 'Broadcast Status Siaga ke Orang Tua & Guru', 'done' => false],
                    ],
                ],
            ],
            'parentUpdates' => [
                [
                    'id' => 'msg-1',
                    'studentName' => 'Brian Aditya',
                    'parentName' => 'Hadi Wicaksono',
                    'category' => 'Notifikasi Kehadiran',
                    'message' => 'Pemberitahuan ketidakhadiran Brian pada hari Kamis, 24 September tanpa surat izin.',
                    'date' => '24 Sep, 08:15',
                    'status' => 'Terkirim via WhatsApp & App',
                    'acknowledgement' => 'Sudah membaca',
                ],
                [
                    'id' => 'msg-2',
                    'studentName' => 'Ahmad Fauzan',
                    'parentName' => 'Rukmini Fauzan',
                    'category' => 'Undangan Konsultasi BK',
                    'message' => 'Undangan diskusi pendampingan kedisiplinan siswa di ruang BK pada hari Jumat.',
                    'date' => '24 Sep, 10:30',
                    'status' => 'Menunggu Respon',
                    'acknowledgement' => 'Perlu ditindaklanjuti',
                ],
            ],
        ]);
    }
}
